// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: todo.proto

package todo_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNSPECIFIED Status = 0
	Status_INCOMPLETE  Status = 1
	Status_COMPLETE    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INCOMPLETE",
		2: "COMPLETE",
	}
	Status_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INCOMPLETE":  1,
		"COMPLETE":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_todo_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_todo_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{0}
}

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Limit         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Status        Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=proto.todo.v1.Status" json:"status,omitempty"`
	IsActivate    bool                   `protobuf:"varint,7,opt,name=is_activate,json=isActivate,proto3" json:"is_activate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetLimit() *timestamppb.Timestamp {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *Todo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Todo) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

func (x *Todo) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNSPECIFIED
}

func (x *Todo) GetIsActivate() bool {
	if x != nil {
		return x.IsActivate
	}
	return false
}

type TodoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*Todo                `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoList) Reset() {
	*x = TodoList{}
	mi := &file_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoList) ProtoMessage() {}

func (x *TodoList) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoList.ProtoReflect.Descriptor instead.
func (*TodoList) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoList) GetResult() []*Todo {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetALLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetALLRequest) Reset() {
	*x = GetALLRequest{}
	mi := &file_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetALLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetALLRequest) ProtoMessage() {}

func (x *GetALLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetALLRequest.ProtoReflect.Descriptor instead.
func (*GetALLRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{2}
}

func (x *GetALLRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type TodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Todo                  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoResponse) Reset() {
	*x = TodoResponse{}
	mi := &file_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoResponse) ProtoMessage() {}

func (x *TodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoResponse.ProtoReflect.Descriptor instead.
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{4}
}

func (x *TodoResponse) GetResult() *Todo {
	if x != nil {
		return x.Result
	}
	return nil
}

type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewTodo       *Todo                  `protobuf:"bytes,1,opt,name=new_todo,json=newTodo,proto3" json:"new_todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTodoRequest) GetNewTodo() *Todo {
	if x != nil {
		return x.NewTodo
	}
	return nil
}

type CreateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoResponse) Reset() {
	*x = CreateTodoResponse{}
	mi := &file_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoResponse) ProtoMessage() {}

func (x *CreateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTodoResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type NotifyStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desier        bool                   `protobuf:"varint,1,opt,name=desier,proto3" json:"desier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyStreamRequest) Reset() {
	*x = NotifyStreamRequest{}
	mi := &file_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyStreamRequest) ProtoMessage() {}

func (x *NotifyStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyStreamRequest.ProtoReflect.Descriptor instead.
func (*NotifyStreamRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyStreamRequest) GetDesier() bool {
	if x != nil {
		return x.Desier
	}
	return false
}

type NotifyStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyTodo    *Todo                  `protobuf:"bytes,1,opt,name=notify_todo,json=notifyTodo,proto3" json:"notify_todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyStreamResponse) Reset() {
	*x = NotifyStreamResponse{}
	mi := &file_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyStreamResponse) ProtoMessage() {}

func (x *NotifyStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyStreamResponse.ProtoReflect.Descriptor instead.
func (*NotifyStreamResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyStreamResponse) GetNotifyTodo() *Todo {
	if x != nil {
		return x.NotifyTodo
	}
	return nil
}

var File_todo_proto protoreflect.FileDescriptor

const file_todo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"todo.proto\x12\rproto.todo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n" +
	"\x04Todo\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x05limit\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05limit\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tupdate_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bupdateAt\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.proto.todo.v1.StatusR\x06status\x12\x1f\n" +
	"\vis_activate\x18\a \x01(\bR\n" +
	"isActivate\"7\n" +
	"\bTodoList\x12+\n" +
	"\x06Result\x18\x01 \x03(\v2\x13.proto.todo.v1.TodoR\x06Result\")\n" +
	"\rGetALLRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\";\n" +
	"\fTodoResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\v2\x13.proto.todo.v1.TodoR\x06result\"C\n" +
	"\x11CreateTodoRequest\x12.\n" +
	"\bnew_todo\x18\x01 \x01(\v2\x13.proto.todo.v1.TodoR\anewTodo\",\n" +
	"\x12CreateTodoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"-\n" +
	"\x13NotifyStreamRequest\x12\x16\n" +
	"\x06desier\x18\x01 \x01(\bR\x06desier\"L\n" +
	"\x14NotifyStreamResponse\x124\n" +
	"\vnotify_todo\x18\x01 \x01(\v2\x13.proto.todo.v1.TodoR\n" +
	"notifyTodo*7\n" +
	"\x06Status\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"INCOMPLETE\x10\x01\x12\f\n" +
	"\bCOMPLETE\x10\x022\xf2\x01\n" +
	"\vTodoService\x12S\n" +
	"\n" +
	"CreateTodo\x12 .proto.todo.v1.CreateTodoRequest\x1a!.proto.todo.v1.CreateTodoResponse\"\x00\x12E\n" +
	"\n" +
	"GetAllTodo\x12\x1c.proto.todo.v1.GetALLRequest\x1a\x17.proto.todo.v1.TodoList\"\x00\x12G\n" +
	"\bFindTodo\x12\x1c.proto.todo.v1.SearchRequest\x1a\x17.proto.todo.v1.TodoList\"\x00(\x010\x01B.Z,api_server/internal/grpc_gen/todo/v1;todo_v1b\x06proto3"

var (
	file_todo_proto_rawDescOnce sync.Once
	file_todo_proto_rawDescData []byte
)

func file_todo_proto_rawDescGZIP() []byte {
	file_todo_proto_rawDescOnce.Do(func() {
		file_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)))
	})
	return file_todo_proto_rawDescData
}

var file_todo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_todo_proto_goTypes = []any{
	(Status)(0),                   // 0: proto.todo.v1.Status
	(*Todo)(nil),                  // 1: proto.todo.v1.Todo
	(*TodoList)(nil),              // 2: proto.todo.v1.TodoList
	(*GetALLRequest)(nil),         // 3: proto.todo.v1.GetALLRequest
	(*SearchRequest)(nil),         // 4: proto.todo.v1.SearchRequest
	(*TodoResponse)(nil),          // 5: proto.todo.v1.TodoResponse
	(*CreateTodoRequest)(nil),     // 6: proto.todo.v1.CreateTodoRequest
	(*CreateTodoResponse)(nil),    // 7: proto.todo.v1.CreateTodoResponse
	(*NotifyStreamRequest)(nil),   // 8: proto.todo.v1.NotifyStreamRequest
	(*NotifyStreamResponse)(nil),  // 9: proto.todo.v1.NotifyStreamResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_todo_proto_depIdxs = []int32{
	10, // 0: proto.todo.v1.Todo.limit:type_name -> google.protobuf.Timestamp
	10, // 1: proto.todo.v1.Todo.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: proto.todo.v1.Todo.update_at:type_name -> google.protobuf.Timestamp
	0,  // 3: proto.todo.v1.Todo.status:type_name -> proto.todo.v1.Status
	1,  // 4: proto.todo.v1.TodoList.Result:type_name -> proto.todo.v1.Todo
	1,  // 5: proto.todo.v1.TodoResponse.result:type_name -> proto.todo.v1.Todo
	1,  // 6: proto.todo.v1.CreateTodoRequest.new_todo:type_name -> proto.todo.v1.Todo
	1,  // 7: proto.todo.v1.NotifyStreamResponse.notify_todo:type_name -> proto.todo.v1.Todo
	6,  // 8: proto.todo.v1.TodoService.CreateTodo:input_type -> proto.todo.v1.CreateTodoRequest
	3,  // 9: proto.todo.v1.TodoService.GetAllTodo:input_type -> proto.todo.v1.GetALLRequest
	4,  // 10: proto.todo.v1.TodoService.FindTodo:input_type -> proto.todo.v1.SearchRequest
	7,  // 11: proto.todo.v1.TodoService.CreateTodo:output_type -> proto.todo.v1.CreateTodoResponse
	2,  // 12: proto.todo.v1.TodoService.GetAllTodo:output_type -> proto.todo.v1.TodoList
	2,  // 13: proto.todo.v1.TodoService.FindTodo:output_type -> proto.todo.v1.TodoList
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_todo_proto_init() }
func file_todo_proto_init() {
	if File_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_proto_goTypes,
		DependencyIndexes: file_todo_proto_depIdxs,
		EnumInfos:         file_todo_proto_enumTypes,
		MessageInfos:      file_todo_proto_msgTypes,
	}.Build()
	File_todo_proto = out.File
	file_todo_proto_goTypes = nil
	file_todo_proto_depIdxs = nil
}
