// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: todo.proto

package todov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_INCOMPLETE Status = 0
	Status_COMPLETE   Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "INCOMPLETE",
		1: "COMPLETE",
	}
	Status_value = map[string]int32{
		"INCOMPLETE": 0,
		"COMPLETE":   1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_todo_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_todo_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{0}
}

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LimitTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=limit_time,json=limitTime,proto3" json:"limit_time,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status        Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=proto.todo.v1.Status" json:"status,omitempty"`
	IsActivate    bool                   `protobuf:"varint,8,opt,name=is_activate,json=isActivate,proto3" json:"is_activate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetLimitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LimitTime
	}
	return nil
}

func (x *Todo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Todo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Todo) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_INCOMPLETE
}

func (x *Todo) GetIsActivate() bool {
	if x != nil {
		return x.IsActivate
	}
	return false
}

type TodoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*Todo                `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoListResponse) Reset() {
	*x = TodoListResponse{}
	mi := &file_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoListResponse) ProtoMessage() {}

func (x *TodoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoListResponse.ProtoReflect.Descriptor instead.
func (*TodoListResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{1}
}

func (x *TodoListResponse) GetResult() []*Todo {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TodoListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetALLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	IsSort        bool                   `protobuf:"varint,2,opt,name=is_sort,json=isSort,proto3" json:"is_sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetALLRequest) Reset() {
	*x = GetALLRequest{}
	mi := &file_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetALLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetALLRequest) ProtoMessage() {}

func (x *GetALLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetALLRequest.ProtoReflect.Descriptor instead.
func (*GetALLRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{2}
}

func (x *GetALLRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *GetALLRequest) GetIsSort() bool {
	if x != nil {
		return x.IsSort
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type TodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Todo                  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoResponse) Reset() {
	*x = TodoResponse{}
	mi := &file_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoResponse) ProtoMessage() {}

func (x *TodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoResponse.ProtoReflect.Descriptor instead.
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{4}
}

func (x *TodoResponse) GetResult() *Todo {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TodoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestTodo   *Todo                  `protobuf:"bytes,1,opt,name=request_todo,json=requestTodo,proto3" json:"request_todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTodoRequest) GetRequestTodo() *Todo {
	if x != nil {
		return x.RequestTodo
	}
	return nil
}

type CreateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	CreatedTodo   *Todo                  `protobuf:"bytes,2,opt,name=created_todo,json=createdTodo,proto3" json:"created_todo,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoResponse) Reset() {
	*x = CreateTodoResponse{}
	mi := &file_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoResponse) ProtoMessage() {}

func (x *CreateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTodoResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *CreateTodoResponse) GetCreatedTodo() *Todo {
	if x != nil {
		return x.CreatedTodo
	}
	return nil
}

func (x *CreateTodoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NotifyStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desier        bool                   `protobuf:"varint,1,opt,name=desier,proto3" json:"desier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyStreamRequest) Reset() {
	*x = NotifyStreamRequest{}
	mi := &file_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyStreamRequest) ProtoMessage() {}

func (x *NotifyStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyStreamRequest.ProtoReflect.Descriptor instead.
func (*NotifyStreamRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyStreamRequest) GetDesier() bool {
	if x != nil {
		return x.Desier
	}
	return false
}

type NotifyStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyTodo    *Todo                  `protobuf:"bytes,1,opt,name=notify_todo,json=notifyTodo,proto3" json:"notify_todo,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyStreamResponse) Reset() {
	*x = NotifyStreamResponse{}
	mi := &file_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyStreamResponse) ProtoMessage() {}

func (x *NotifyStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyStreamResponse.ProtoReflect.Descriptor instead.
func (*NotifyStreamResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyStreamResponse) GetNotifyTodo() *Todo {
	if x != nil {
		return x.NotifyTodo
	}
	return nil
}

func (x *NotifyStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTodoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	AtherTodo     []*Todo                `protobuf:"bytes,2,rep,name=AtherTodo,proto3" json:"AtherTodo,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoResponse) Reset() {
	*x = DeleteTodoResponse{}
	mi := &file_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoResponse) ProtoMessage() {}

func (x *DeleteTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoResponse.ProtoReflect.Descriptor instead.
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTodoResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *DeleteTodoResponse) GetAtherTodo() []*Todo {
	if x != nil {
		return x.AtherTodo
	}
	return nil
}

func (x *DeleteTodoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_todo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTodoRequest) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type UpdateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoResponse) Reset() {
	*x = UpdateTodoResponse{}
	mi := &file_todo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoResponse) ProtoMessage() {}

func (x *UpdateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoResponse.ProtoReflect.Descriptor instead.
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTodoResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *UpdateTodoResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_todo_proto protoreflect.FileDescriptor

const file_todo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"todo.proto\x12\rproto.todo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x04Todo\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"limit_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlimitTime\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.proto.todo.v1.StatusR\x06status\x12\x1f\n" +
	"\vis_activate\x18\b \x01(\bR\n" +
	"isActivateB\x05\n" +
	"\x03_id\"U\n" +
	"\x10TodoListResponse\x12+\n" +
	"\x06Result\x18\x01 \x03(\v2\x13.proto.todo.v1.TodoR\x06Result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"B\n" +
	"\rGetALLRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\x12\x17\n" +
	"\ais_sort\x18\x02 \x01(\bR\x06isSort\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"Q\n" +
	"\fTodoResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\v2\x13.proto.todo.v1.TodoR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x11CreateTodoRequest\x126\n" +
	"\frequest_todo\x18\x01 \x01(\v2\x13.proto.todo.v1.TodoR\vrequestTodo\"z\n" +
	"\x12CreateTodoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x126\n" +
	"\fcreated_todo\x18\x02 \x01(\v2\x13.proto.todo.v1.TodoR\vcreatedTodo\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"-\n" +
	"\x13NotifyStreamRequest\x12\x16\n" +
	"\x06desier\x18\x01 \x01(\bR\x06desier\"b\n" +
	"\x14NotifyStreamResponse\x124\n" +
	"\vnotify_todo\x18\x01 \x01(\v2\x13.proto.todo.v1.TodoR\n" +
	"notifyTodo\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"#\n" +
	"\x11DeleteTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"u\n" +
	"\x12DeleteTodoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x121\n" +
	"\tAtherTodo\x18\x02 \x03(\v2\x13.proto.todo.v1.TodoR\tAtherTodo\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"<\n" +
	"\x11UpdateTodoRequest\x12'\n" +
	"\x04todo\x18\x01 \x01(\v2\x13.proto.todo.v1.TodoR\x04todo\">\n" +
	"\x12UpdateTodoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err*&\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"INCOMPLETE\x10\x00\x12\f\n" +
	"\bCOMPLETE\x10\x012\xac\x03\n" +
	"\vTodoService\x12S\n" +
	"\n" +
	"CreateTodo\x12 .proto.todo.v1.CreateTodoRequest\x1a!.proto.todo.v1.CreateTodoResponse\"\x00\x12M\n" +
	"\n" +
	"GetAllTodo\x12\x1c.proto.todo.v1.GetALLRequest\x1a\x1f.proto.todo.v1.TodoListResponse\"\x00\x12O\n" +
	"\bFindTodo\x12\x1c.proto.todo.v1.SearchRequest\x1a\x1f.proto.todo.v1.TodoListResponse\"\x00(\x010\x01\x12S\n" +
	"\n" +
	"UpdateTodo\x12 .proto.todo.v1.UpdateTodoRequest\x1a!.proto.todo.v1.UpdateTodoResponse\"\x00\x12S\n" +
	"\n" +
	"DeleteTodo\x12 .proto.todo.v1.DeleteTodoRequest\x1a!.proto.todo.v1.DeleteTodoResponse\"\x00B\x9a\x01\n" +
	"\x11com.proto.todo.v1B\tTodoProtoP\x01Z$api/internal/grpc_gen/todo/v1;todov1\xa2\x02\x03PTX\xaa\x02\rProto.Todo.V1\xca\x02\rProto\\Todo\\V1\xe2\x02\x19Proto\\Todo\\V1\\GPBMetadata\xea\x02\x0fProto::Todo::V1b\x06proto3"

var (
	file_todo_proto_rawDescOnce sync.Once
	file_todo_proto_rawDescData []byte
)

func file_todo_proto_rawDescGZIP() []byte {
	file_todo_proto_rawDescOnce.Do(func() {
		file_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)))
	})
	return file_todo_proto_rawDescData
}

var file_todo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_todo_proto_goTypes = []any{
	(Status)(0),                   // 0: proto.todo.v1.Status
	(*Todo)(nil),                  // 1: proto.todo.v1.Todo
	(*TodoListResponse)(nil),      // 2: proto.todo.v1.TodoListResponse
	(*GetALLRequest)(nil),         // 3: proto.todo.v1.GetALLRequest
	(*SearchRequest)(nil),         // 4: proto.todo.v1.SearchRequest
	(*TodoResponse)(nil),          // 5: proto.todo.v1.TodoResponse
	(*CreateTodoRequest)(nil),     // 6: proto.todo.v1.CreateTodoRequest
	(*CreateTodoResponse)(nil),    // 7: proto.todo.v1.CreateTodoResponse
	(*NotifyStreamRequest)(nil),   // 8: proto.todo.v1.NotifyStreamRequest
	(*NotifyStreamResponse)(nil),  // 9: proto.todo.v1.NotifyStreamResponse
	(*DeleteTodoRequest)(nil),     // 10: proto.todo.v1.DeleteTodoRequest
	(*DeleteTodoResponse)(nil),    // 11: proto.todo.v1.DeleteTodoResponse
	(*UpdateTodoRequest)(nil),     // 12: proto.todo.v1.UpdateTodoRequest
	(*UpdateTodoResponse)(nil),    // 13: proto.todo.v1.UpdateTodoResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_todo_proto_depIdxs = []int32{
	14, // 0: proto.todo.v1.Todo.limit_time:type_name -> google.protobuf.Timestamp
	14, // 1: proto.todo.v1.Todo.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: proto.todo.v1.Todo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: proto.todo.v1.Todo.status:type_name -> proto.todo.v1.Status
	1,  // 4: proto.todo.v1.TodoListResponse.Result:type_name -> proto.todo.v1.Todo
	1,  // 5: proto.todo.v1.TodoResponse.result:type_name -> proto.todo.v1.Todo
	1,  // 6: proto.todo.v1.CreateTodoRequest.request_todo:type_name -> proto.todo.v1.Todo
	1,  // 7: proto.todo.v1.CreateTodoResponse.created_todo:type_name -> proto.todo.v1.Todo
	1,  // 8: proto.todo.v1.NotifyStreamResponse.notify_todo:type_name -> proto.todo.v1.Todo
	1,  // 9: proto.todo.v1.DeleteTodoResponse.AtherTodo:type_name -> proto.todo.v1.Todo
	1,  // 10: proto.todo.v1.UpdateTodoRequest.todo:type_name -> proto.todo.v1.Todo
	6,  // 11: proto.todo.v1.TodoService.CreateTodo:input_type -> proto.todo.v1.CreateTodoRequest
	3,  // 12: proto.todo.v1.TodoService.GetAllTodo:input_type -> proto.todo.v1.GetALLRequest
	4,  // 13: proto.todo.v1.TodoService.FindTodo:input_type -> proto.todo.v1.SearchRequest
	12, // 14: proto.todo.v1.TodoService.UpdateTodo:input_type -> proto.todo.v1.UpdateTodoRequest
	10, // 15: proto.todo.v1.TodoService.DeleteTodo:input_type -> proto.todo.v1.DeleteTodoRequest
	7,  // 16: proto.todo.v1.TodoService.CreateTodo:output_type -> proto.todo.v1.CreateTodoResponse
	2,  // 17: proto.todo.v1.TodoService.GetAllTodo:output_type -> proto.todo.v1.TodoListResponse
	2,  // 18: proto.todo.v1.TodoService.FindTodo:output_type -> proto.todo.v1.TodoListResponse
	13, // 19: proto.todo.v1.TodoService.UpdateTodo:output_type -> proto.todo.v1.UpdateTodoResponse
	11, // 20: proto.todo.v1.TodoService.DeleteTodo:output_type -> proto.todo.v1.DeleteTodoResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_todo_proto_init() }
func file_todo_proto_init() {
	if File_todo_proto != nil {
		return
	}
	file_todo_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_proto_rawDesc), len(file_todo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_proto_goTypes,
		DependencyIndexes: file_todo_proto_depIdxs,
		EnumInfos:         file_todo_proto_enumTypes,
		MessageInfos:      file_todo_proto_msgTypes,
	}.Build()
	File_todo_proto = out.File
	file_todo_proto_goTypes = nil
	file_todo_proto_depIdxs = nil
}
