

services:
#   api_server:
#     build:
#       dockerfile: ./api_server/Dockerfile
#     env_file:
#       - .env.mysql
#     networks:
#       - backend
#     depends_on:
#       - db


  
  db:
    image: mysql:latest
    restart: always
    env_file: 
      - .env.mysql
    ports:
      - "3306:3306"
      - "3306"
    # volumes:
    #   - ./scripts:/docker-entrypoint-initdb.d
#     networks:
#       - backend

# networks:
#   backend:
#     driver: custom-driver-1



# サンプルアプリなので永続化の設定は行いませんでした。


