

services:
  api_server:
    build:
      context: ./api_server
      # dockerfile: ./api_server/Dockerfile
    env_file:
      - ./env_files/.env.mysql
      - ./env_files/.env.go_server
    command: ["/app/bin/execute_go"]
    
    ports:
      - "8080:8080"
      - "8080"
    
    depends_on:
      - db


  
  db:
    image: mysql:latest
    restart: always
    env_file: 
      - ./env_files/.env.mysql
    ports:
      - "3306:3306"
      - "3306"
      
    # volumes:
    #   - ./scripts:/docker-entrypoint-initdb.d
    




# サンプルアプリなので永続化の設定は行いませんでした。


