

services:
  api_server:
    build:
      dockerfile: ./api_server/Dockerfile
    env_file:
      - .env.mysql
  
  db:
    image: mysql
    restart: always
    env_file: 
      - .env.mysql

  




# サンプルアプリなので永続化の設定は行いませんでした。


