

services:
  api_server:
    build:
      context: ./api_server
      # dockerfile: ./api_server/Dockerfile
    env_file:
      - ./env_files/.env.mysql
      - ./env_files/.env.go_server
    entrypoint: ["/execute_go"]
    ports:
      - "8080:8080"
      - "8080"
    
    depends_on:
      db:
        condition: service_healthy


  
  db:
    image: mysql:latest
    restart: always
    env_file: 
      - ./env_files/.env.mysql
    ports:
      - "3306:3306"
      - "3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 5s
      timeout: 20s
      retries: 20
      start_period: 1s
      
    # volumes:
    #   - ./scripts:/docker-entrypoint-initdb.d
    




# サンプルアプリなので永続化の設定は行いませんでした。


