

services:
  # api_server:
  #   build:
  #     dockerfile: ./api_server/Dockerfile
  #   env_file:
  #     - .env.mysql
  #   depends_on:
  #     - db

  
  db:
    image: mysql
    restart: always
    env_file: 
      - .env.mysql
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  




# サンプルアプリなので永続化の設定は行いませんでした。


